# Generated by Django 3.0 on 2026-04-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_profiles(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')
    for profile in OldProfile.objects.all():
        NewProfile.objects.create(
            user=profile.user,
            favorite_city=profile.favorite_city,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oc_lettings_site', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_city', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(copy_profiles),
    ]
